[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "xrepc"
version = "0.1.0"
license = { text = "MIT" }
description = "A Python package for Byzantine-resilient distributed consensus using the Expressive Reputation-based Consensus (XRepC) algorithm."
authors = [{ name = "Rui Huang", email = "ruihuang0421@gmail.com" }]

dependencies = [
    "scipy>=1.15.3",
    "topolink @ git+https://github.com/rui-huang-opt/topolink.git@0.2.0",
]

[project.optional-dependencies]
vsc = ["ipykernel>=6.29.5"]

[tool.setuptools.packages.find]
where = ["src"]
